#!/bin/bash

# Copyright (C) 2017 Intel Corporation
# SPDX-License-Identifier: MIT

TMP=$(mktemp)

ps aux > $TMP

cat $TMP | grep "$@"
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo "IS NOT RUNNING OK for '$@'"
else
    echo "IS NOT RUNNING FAIL for '$@'"
fi
